name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install emscripten
      uses: lovasoa/setup-emscripten@master
      with:
        emscripten-version: '2.0.27'
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: Build
      run: |
        mkdir build
        cd build
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
        emmake make

