name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v10
      with:
        version: 2.0.27
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: Build
      run: |
        mkdir build
        cd build
        emcmake cmake .. -DCMAKE_BUILD_TYPE=Release
        emmake make

